DEFAULT_SERVER_PORT = "7777"
DEFAULT_SERVER_LISTEN_ADDRESS = ""
DEFAULT_SERVER_ADDRESS = "127.0.0.1"
MAX_CONNECTIONS = 5
MAX_DATA_LENGTH = 1024
ENCODING_VAR = "utf-8"

ALLOWED_ACTION_LIST = ("presence", "quit")
USER_LIST = ("Nik", "Guest")
